- name: Directory is present
  file:
    path=/data/books-service/db
    state=directory
  tags: [books-service]

- name: Latest containers are pulled
  shell: sudo docker pull 192.168.50.91:5000/{{ item }}
  with_items: images
  tags: [books-service]

- name: Containers are absent
  docker:
    image: 192.168.50.91:5000/{{ item }}
    name: "{{ item }}"
    state: absent
  with_items: images
  tags: [books-service]

- name: Container is running
  docker:
    name: books-service
    image: 192.168.50.91:5000/books-service
    ports: 9001:8080
    volumes: /data/books-service/db:/data/db
    state: running
  tags: [books-service]

- name: Integration tests are copied
  copy: src=books-service-integ.sh dest=/opt/books-service-integ.sh
  tags: [books-service]

- name: Integration tests are run
  shell: /opt/books-service-integ.sh
  tags: [books-service]